config/routes.rb
Rails.application.routes.draw do
  scope :api do
    scope :v1 do
      get 'dragons' => 'dragon_cards#index'
      get 'user' => 'users#show'
      get 'users' => 'users#index'
      post 'users' => 'users#create'
      get 'room' => 'rooms#show'
      get 'rooms' => 'rooms#index'
      post 'rooms' => 'rooms#create'
      post 'rooms/seats/take' => 'rooms#take_seat'
      post 'rooms/seats/leave' => 'rooms#leave_seat'

      post 'game/start'  => 'rooms#game_start'
      post 'game/finger' => 'rooms#cast_finger'
      post 'game/name'   => 'rooms#cast_name'
      post 'game/ok'     => 'rooms#cast_ok'
    end
  end

end

app/models/dragon_card.rb
# encoding: utf-8
class DragonCard < ActiveRecord::Base
  include Comparable

  def <=>(other)
    self.atk <=> other.atk
  end

  def success? current_user,me,all_finger
    my_finger = me.finger
    case self.short_name
    when :推理
      if my_finger == 1
        right_card_id = me.right_person.user_game_infomation.dragon_card_id
        me.user_game_infomation.called_dragon_card_id == right_card_id
      else
        false
      end
    when :運命
      map = {0=>2,2=>5,5=>0}
      all_finger.include? (map[my_finger])
    when :無双
      all_finger.count(my_finger) == 1
    when :＋１
      target_number = my_finger==0? 5 : my_finger - 1
      all_finger.include? target_number
    when :最大
      my_finger == all_finger.max
    when :奇数
      my_finger % 2 == 1
    when :なし
      true
    else
      false
    end
  end

  def short_name
    case self.id
    when 0 then :推理
    when 1 then :運命
    when 2 then :無双
    when 3 then :＋１
    when 4 then :最大
    when 5 then :奇数
    when 6 then :なし
    end
  end
end

app/controllers/dragon_cards_controller.rb
class DragonCardsController < ApplicationController
  def index
    render_json DragonCard.all
  end
end

app/helpers/dragon_cards_helper.rb
module DragonCardsHelper
end

app/views/dragon_cards/_form.html.erb
<%= form_for(@dragon_card) do |f| %>
  <% if @dragon_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dragon_card.errors.count, "error") %> prohibited this dragon_card from being saved:</h2>

      <ul>
      <% @dragon_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_word %><br>
    <%= f.text_field :short_word %>
  </div>
  <div class="field">
    <%= f.label :for_2_players %><br>
    <%= f.text_field :for_2_players %>
  </div>
  <div class="field">
    <%= f.label :for_3_players %><br>
    <%= f.text_field :for_3_players %>
  </div>
  <div class="field">
    <%= f.label :for_4_players %><br>
    <%= f.text_field :for_4_players %>
  </div>
  <div class="field">
    <%= f.label :main_text %><br>
    <%= f.text_field :main_text %>
  </div>
  <div class="field">
    <%= f.label :flavor_text %><br>
    <%= f.text_field :flavor_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dragon_cards/edit.html.erb
<h1>Editing Dragon Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @dragon_card %> |
<%= link_to 'Back', dragon_cards_path %>

app/views/dragon_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dragon Cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short word</th>
      <th>For 2 players</th>
      <th>For 3 players</th>
      <th>For 4 players</th>
      <th>Main text</th>
      <th>Flavor text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dragon_cards.each do |dragon_card| %>
      <tr>
        <td><%= dragon_card.name %></td>
        <td><%= dragon_card.short_word %></td>
        <td><%= dragon_card.for_2_players %></td>
        <td><%= dragon_card.for_3_players %></td>
        <td><%= dragon_card.for_4_players %></td>
        <td><%= dragon_card.main_text %></td>
        <td><%= dragon_card.flavor_text %></td>
        <td><%= link_to 'Show', dragon_card %></td>
        <td><%= link_to 'Edit', edit_dragon_card_path(dragon_card) %></td>
        <td><%= link_to 'Destroy', dragon_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dragon card', new_dragon_card_path %>

app/views/dragon_cards/new.html.erb
<h1>New Dragon Card</h1>

<%= render 'form' %>

<%= link_to 'Back', dragon_cards_path %>

app/views/dragon_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dragon_card.name %>
</p>

<p>
  <strong>Short word:</strong>
  <%= @dragon_card.short_word %>
</p>

<p>
  <strong>For 2 players:</strong>
  <%= @dragon_card.for_2_players %>
</p>

<p>
  <strong>For 3 players:</strong>
  <%= @dragon_card.for_3_players %>
</p>

<p>
  <strong>For 4 players:</strong>
  <%= @dragon_card.for_4_players %>
</p>

<p>
  <strong>Main text:</strong>
  <%= @dragon_card.main_text %>
</p>

<p>
  <strong>Flavor text:</strong>
  <%= @dragon_card.flavor_text %>
</p>

<%= link_to 'Edit', edit_dragon_card_path(@dragon_card) %> |
<%= link_to 'Back', dragon_cards_path %>